sudo: true
language: python
python:
 - "3.3"
 - "3.4"
env:
  matrix:
install:
 - sudo apt-get install -y build-essential g++ git subversion automake libtool zlib1g-dev libboost-all-dev libbz2-dev liblzma-dev python3-dev libgoogle-perftools-dev libxmlrpc-c++.*-dev
 - pip install https://github.com/rsennrich/Bleualign/archive/master.zip
 - pip install https://github.com/kpu/kenlm/archive/master.zip
 - pip install https://github.com/sih4sing5hong5/hts_engine_python/archive/master.zip
 - pip install flake8
 - pip install coverage
branches:
 only:
  - master
script:
 - pip install .
 - python 範例/基本元素.py
 - python 範例/斷詞範例.py
 - python 範例/轉拼音系統.py
 - python 走全部試驗.py 單元試驗
 - coverage run 走全部試驗.py
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
after_script:
 - flake8 . --exclude=venv,外部程式 --count --show-source --ignore=E251,E101,W191,W291,W293,E501
